# Use an official PHP runtime as a parent image
FROM php:7.4-apache

# Set the working directory in the container to /var/www/html
WORKDIR /var/www/html

# Copy the current directory contents into the container at /var/www/html
COPY . /var/www/html

# Expose port 80
EXPOSE 80

# Use the Apache server .htaccess
RUN a2enmod rewrite

# Start Apache service
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]